### GET ALL
GET http://localhost:5000/test

### GET ONE
GET http://localhost:5000/test/1

### CREATE
POST http://localhost:5000/test
Content-Type: application/json

{
  "aaa": "123",
  "bbbb": "121"
}

### UPDATE
PUT http://localhost:5000/test/1
Content-Type: application/json

{
  "aaa": "123zefrfre",
  "bbbb": "12gerrgege1"
}

### DELETE
DELETE http://localhost:5000/test/1